[tools]
aws = { version = "2.36.40", symlink_bins = "true" }
bun = "1.4.0"
claude = "latest"
codex = "0.152.0"
devcontainer-cli = "0.89.0"
duckdb = "1.5.5"
gh = "2.99.0"
go = "1.27.1"
jq = "1.8.2"
mysql = "8.0.34"
node = "26.8.1"
pnpm = "12.3.1"
pre-commit = "4.6.2"
python = "3.14.7"
ripgrep = "15.2.0"
terraform = "1.16.1"
tflint = "0.64.0"
tmux = "3.7"
trivy = "0.74.0"
vim = "latest"

[settings]
experimental = true
paranoid = true
install_before = "3d"
